### PR TITLE
Forgot the definition for 4in1

### PR DESCRIPTION
**Pull request by tipouic**
Hello, first of all, thank you very much for the port on the ESP32.

I would like to make myself a great 6in1 module by adding the E28 and the SX1276/RFM95W to a 4in1 module.

I get some compilation errors that I could solve (this pull-resquest) but I still have a problem with the A7105 because the definition of the "SPI_SDI_Read()" function is missing in the "SPI.ino" file for the "ESPxx_PLATEFORM".

Thanks in advance

### CODE REVIEW

**Comment by midelic** [comment]
I made a major update planned long time before your PR. Can you update you fork and check your PR against the new update?
If ok I will merge it.

**Comment by tipouic** [comment]
I just looked at the files that have moved and there are none of my files that are in there because it must be not followed / or forgotten updates.

On the other hand, the definition of the "SPI_SDI_Read()" function is still missing in the "SPI.ino" file for the ESP platforms unless we can reuse that of the STM32.
https://github.com/tipouic/DIY-Multiprotocol-TX-Module/blob/patch-1/Multiprotocol/SPI.ino#L60 for STM32
or
https://github.com/tipouic/DIY-Multiprotocol-TX-Module/blob/patch-1/Multiprotocol/SPI.ino#L157 for AVR

**Comment by midelic** [comment]
SPI_SDI_Read() It is missing because A7105 is using bidirectional 3 wire SPI communication.STM32 has HW SPI code adapted  for that. I have to look in ESP32 documentation if I can find something. O maybe use bit banging as AVR used.I suggest for the moment use bit banging(AVR spi code) .You can copy it to #ifdef ESP32_PLATFORM.

**Comment by tipouic** [comment]
ok, that's nice because i have a lot of small receiver in flysky.
For the moment, I am waiting for the delivery of my esp32 wrover but I test before. And after, if I manage to make everything work, I try to make a new internal module PCB for my jumper t-lite

**Comment by midelic** [comment]
merged

**Pull request merged**
